baseURL = "https://bortox.it/contribuisci-cs-en"
languageCode = "en"
defaultContentLanguage = "en"

title = "Make a donation"
copyright = "I will use these donations to support the costs of the **server** and **domain name**, in addition to my own work. Otherwise, instead of money you can always send your ideas to **improve the website** to bort0x [at] tuta.io!"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Help bortox.it stay ad-free and full of new and interesting content."
  image = "bortox-it.png"  # path relative to static directory
  headline = "Help bortox.it stay ad-free and full of new and interesting content."
  links = [
    { paypal = { href= "https://www.paypal.com/donate/?hosted_button_id=EXM9CJNDTLCZJ", text = "Donate with PayPal" }},
    { stripe = { href= "https://donate.stripe.com/dR69BB66G13t7yo000", text = "Offer me some focaccia 🫓" }},
    { stripe = { href= "https://donate.stripe.com/00gcNN66GaE3f0Q002", text = "Choose how much to give with Stripe" }},
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = {href = "https://github.com/bortox/", text = "Source Code" }},
    # { gitlab = "https://gitlab.com/username" },
    #{ google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { email = { href = "mailto:bortox@bortox.it" , text = "Email" }},
    # { mastodon = "https://mastodon-instance/username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
    { exit = {href="https://bortox.it/en", text="Back to bortox.it 🏠"}},
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
    

